name: Build test
on:
  push:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: bash ci.sh deps
    - name: Building
      run: bash build-tc.sh
      env:
        BTOKEN: ${{ secrets.BTOKEN }}
        GTOKEN: ${{ secrets.GTOKEN }}
